import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const pageSource = readFileSync('src/app/page.tsx', 'utf8');
const loginSource = readFileSync('src/app/login/page.tsx', 'utf8');
const routeSource = readFileSync('src/app/api/me/profile/route.ts', 'utf8');
const migrationSource = readFileSync('supabase/migrations/20260525234000_add_demo_sessions.sql', 'utf8');

const generatedDemoName = (displayNumber) => `demo-user-${String(displayNumber).padStart(3, '0')}`;
assert.equal(generatedDemoName(1), 'demo-user-001');
assert.equal(generatedDemoName(42), 'demo-user-042');

assert.match(migrationSource, /display_number\s+bigint[\s\S]*generated by default as identity/i, 'demo session はDB挿入順の番号を持ってください。');
assert.match(migrationSource, /display_name\s+text[\s\S]*generated always as[\s\S]*demo-user-[\s\S]*lpad\(display_number::text, 3, '0'\)/i, 'demo-user-001 形式の表示名をDB側で生成してください。');

assert.match(routeSource, /userName:\s*profileRow\.name \|\| session\.display_name/, 'demo profile未設定時はDB sessionの自動表示名を返してください。');
assert.match(routeSource, /const\s+userName\s*=\s*payload\.userName\.trim\(\) \|\| session\.display_name/, '空の表示名保存時はDB session表示名へfallbackしてください。');

assert.match(loginSource, /localStorage\.setItem\(DEMO_SESSION_STORAGE_KEY, data\.sessionId\)/, 'one-click demo login はDB session idをlocalStorageへ復元ヒントとして保存してください。');
assert.match(loginSource, /localStorage\.removeItem\(LEGACY_DEMO_PROFILE_STORAGE_KEY\)/, '旧demo profile localStorageは新規DB-backed loginで消してください。');

const demoBranchStart = pageSource.indexOf("if (demoSession.status === 'authenticated')");
assert.notEqual(demoBranchStart, -1, 'demo authenticated branch を検査できません。');
const demoBranch = pageSource.slice(demoBranchStart, pageSource.indexOf("if (demoSession.status === 'failed')", demoBranchStart));
assert.match(demoBranch, /const\s+merged\s*=\s*mergeProfile\(null, remoteProfile\)/, 'demo session はDB profileの表示名を正として復元してください。');
assert.doesNotMatch(pageSource, /function\s+writeDemoProfile\(/, 'DB-backed demoでは表示名を旧demo localStorageに保存しないでください。');

console.log('demo profile name preservation regression checks passed');
