-- =============================================
-- DB-backed demo sessions for presentation mode
-- =============================================
-- Demo users are intentionally isolated from auth.users / profiles.
-- Route Handlers resolve a server-issued demo session cookie and use a
-- server-only admin client to access these tables. Browser anon/authenticated
-- roles receive no direct policies on the demo tables.

create table if not exists public.demo_sessions (
  id             uuid primary key default gen_random_uuid(),
  display_number bigint generated by default as identity unique,
  display_name   text generated always as ('demo-user-' || lpad(display_number::text, 3, '0')) stored,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.demo_profiles (
  session_id                              uuid primary key references public.demo_sessions(id) on delete cascade,
  name                                    text not null,
  preferred_dishes                        text[] not null default '{}'::text[],
  preferred_cuisines                      text[] not null default '{}'::text[],
  non_ingredient_restrictions             text[] not null default '{}'::text[],
  non_ingredient_restriction_reasons      jsonb not null default '{}'::jsonb,
  created_at                              timestamptz not null default now(),
  updated_at                              timestamptz not null default now()
);

create table if not exists public.demo_restricted_ingredients (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references public.demo_sessions(id) on delete cascade,
  ingredient_id uuid not null references public.ingredients(id) on delete cascade,
  reason        text not null default 'allergy',
  created_at    timestamptz not null default now(),
  constraint demo_restricted_ingredients_unique unique (session_id, ingredient_id)
);

create index if not exists demo_restricted_ingredients_session_id_idx
  on public.demo_restricted_ingredients (session_id);

create index if not exists demo_restricted_ingredients_ingredient_id_idx
  on public.demo_restricted_ingredients (ingredient_id);

alter table public.demo_sessions enable row level security;
alter table public.demo_profiles enable row level security;
alter table public.demo_restricted_ingredients enable row level security;

-- Intentionally create no anon/authenticated policies for demo tables.
-- All demo profile access must go through server-only Route Handlers.

comment on table public.demo_sessions is
  'Presentation demo identities. Not linked to auth.users; accessed only by server Route Handlers.';
comment on column public.demo_sessions.display_name is
  'Generated display name such as demo-user-001 based on insertion order.';
comment on table public.demo_profiles is
  'DB-backed profile/preferences for presentation demo sessions.';
comment on table public.demo_restricted_ingredients is
  'Ingredient restrictions selected by presentation demo sessions.';
